name: safe_commute
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  google_mlkit_face_detection: ^0.13.0
  audioplayers: ^6.5.0
  vibration: ^3.1.3
  provider: ^6.1.5
  geolocator: ^9.0.2
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  printing: ^5.12.0  # For PDF tickets
  pdf: ^3.10.7       # For PDF generation
  qr_flutter: ^4.1.0 # For QR on tickets
  
  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets: 
      - assets/sounds/beep.wav
      - assets/sounds/alarm.wav