// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE1QgwebhQ8NL4lcloclFyVWyIzjWmvMY',
    appId: '1:521728664554:web:8ea0a5a61823fef9db4893',
    messagingSenderId: '521728664554',
    projectId: 'safe-commute-cb13b',
    authDomain: 'safe-commute-cb13b.firebaseapp.com',
    storageBucket: 'safe-commute-cb13b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChoi0Vp9eyVmy6fiLKpn8-s25VN5gORvM',
    appId: '1:521728664554:android:3b64ab8dbaab23dadb4893',
    messagingSenderId: '521728664554',
    projectId: 'safe-commute-cb13b',
    storageBucket: 'safe-commute-cb13b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtwjOco43VKlzdDUqioKAPraUqsZTxCLY',
    appId: '1:521728664554:ios:6202837255836d0ddb4893',
    messagingSenderId: '521728664554',
    projectId: 'safe-commute-cb13b',
    storageBucket: 'safe-commute-cb13b.firebasestorage.app',
    iosBundleId: 'com.example.safeCommute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtwjOco43VKlzdDUqioKAPraUqsZTxCLY',
    appId: '1:521728664554:ios:6202837255836d0ddb4893',
    messagingSenderId: '521728664554',
    projectId: 'safe-commute-cb13b',
    storageBucket: 'safe-commute-cb13b.firebasestorage.app',
    iosBundleId: 'com.example.safeCommute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE1QgwebhQ8NL4lcloclFyVWyIzjWmvMY',
    appId: '1:521728664554:web:8bbc4ce3023c31b9db4893',
    messagingSenderId: '521728664554',
    projectId: 'safe-commute-cb13b',
    authDomain: 'safe-commute-cb13b.firebaseapp.com',
    storageBucket: 'safe-commute-cb13b.firebasestorage.app',
  );
}
